### ISSUE TITLE
Enable dimming of icon for unsaved pages

### ISSUE THREAD

**Issue by intafon** [Rami114/pinboard#3]
Per another extension that I currently use (which just does saving with no link for displaying), it would be great if this extension provided visual feedback to indicate that the page had already been saved (or not).

**Comment by Rami114** [comment]
I'll see if there's an API endpoint I can poll to show when a page has been added (or not). This might require the add-on to become aware of your logged-in status (which is not really a bad thing). For now I'm avoiding forcing people to add API keys.

**Comment by Rami114** [comment]
Scrap that, looks like this kind of thing will require API keys. I'll make it optional though, means it'll be a bit more work but that's ok.

**Comment by Rami114** [comment]
This is in progress now, added:

- Settings screen in about:addons to put API-key (optional)
- Address bar menu will show you the API key status (none, added-and-good, added-but-bad, network-issues)
- Automatic 5-minute polling 

Remaining:

- Add function to poll for current URL status in Pinboard
- Add handlers to switch icons depending on URL status

@intafon I'm thinking of adding a green tick to the icon if it's already been added, otherwise the current icon will remain.

**Comment by intafon** [comment]
Cool, thanks!
I'm not sure polling for current URL status is really vital unless I am misunderstanding your intent. In most cases I think checking to see if the current URL is saved on page load is sufficient (unless that is what you mean) -- unless the plugin isn't able to get page change/load events...

**Comment by Rami114** [comment]
The polling is for the API key being correct, and the API being accessible. It's a nice-to-have but I'm used to having it so I put it in. Hopefully will be able to release this soon.

**Comment by Rami114** [comment]
Minor version increment which adds:

* Ability to add (optional) Pinboard API key via about:addons
* When API key is provided, API status is shown in the address bar drop-down
* With valid API key the icon will show a green tick in the address bar if this URL was previously bookmarked

**Comment by Rami114** [comment]
It's not dimming, rather it's a green tick. Right now it updates on URL reload, because forcing a reload asynchronously is difficult and we shouldn't poll all the time as the API call isn't that lightweight (and Pinboard will slaughter me if I poll it constantly).

**Comment by Rami114** [comment]
Initial feature is now in, we now support the API so we are open to adding more features backed by it.
