### ISSUE TITLE
Pop-up window for bookmarking

### ISSUE THREAD

**Issue by sallymaria** [Rami114/pinboard#4]
Would it be possible for the bookmarking dialog to be a pop-up window, rather than a tab? It's much tidier, and makes it easier to copy across information from the page you are bookmarking.

**Comment by Rami114** [comment]
Yep, I think that's a good idea, I didn't like the tab opening at the end of the tab-list anyway. Popup makes sense.

**Comment by Rami114** [comment]
Applied in a2106ee

**Comment by Rami114** [comment]
Version 1.0.1 should be visible in a minute that does this.
